### PR TITLE
Aspect Logger for Controllers

### LINKED ISSUE #3: Add Aspect for Logging Controllers
Create Aspect for Logging Controllers

### PR DESCRIPTION
**Pull request by Zond47**

### CODE REVIEW

**Comment by ChernoVl** [comment]
I think it's good setting up .gitignore file so that changes from the target are not added. Create a new issue?

**Comment by Zond47** [comment]
> I think it's good setting up .gitignore file so that changes from the target are not added. Create a new issue?

Create .gitignore, anyway I send files through github.com

**Review by makaceli — COMMENTED** [review]
I agree with vlad to add target files to .ignore

**Comment by Zond47** [comment]
> I agree with vlad to add target files to .ignore

Please write relevant comments to the topic, there are already issue with .gitignore you welcome to complete

**Pull request closed without merging**
